spring:
  application:
    name: zuul-server
server:
  port: 5555
  servlet:
    context-path: /cloud
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    frontend-service: /students/**
  sensitiveHeaders: Cookie, Set-Cookie
ribbon:
  ReadTimeout: 60000